# Generated by Django 3.0.3 on 2020-02-23 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needToSpend', models.DecimalField(decimal_places=2, max_digits=14)),
                ('checkAmount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('percentGoal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ntsDuration', models.CharField(max_length=21)),
                ('currentSpending', models.ManyToManyField(blank=True, to='goals.Spending')),
                ('spender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
