# Generated by Django 3.0.3 on 2020-02-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20200224_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='percentSpendingFromCheck',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='goal',
            name='totalSpending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
